---
# Apply the roles on all VMs in the group 'bwCloud'.
- hosts: bwCloud
  tags: [all]
  roles:
    # Associate the role 'XY' with the tag 'XY'
    - { role: apt, tags: [apt] }
    - { role: network, tags: [network] }
    - { role: basics, tags: [basics] }
    - { role: shell, tags: [shell] }
    - { role: python_env, tags: [python_env] }
    - { role: openstack_client, tags: [openstack_client] }

